version: '3.8'

services:
  mlops-app:
    build: .
    volumes:
      - ../mlops/data:/app/data  
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped